# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Deploy Website
on:
  push:
    branches:
      - main
    paths:
      - "front-end/**"
      - ".github/workflows/fly-web.yml"

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          flyctl deploy --remote-only \
          --build-arg VITE_REOWN_PROJECT_ID=${{ secrets.VITE_REOWN_PROJECT_ID }} \
          --build-arg VITE_JWT_IPFS=${{ secrets.VITE_JWT_IPFS }} \
          --build-arg VITE_API_KEY_IPFS=${{ secrets.VITE_API_KEY_IPFS }} \
          --build-arg VITE_API_SECRET_IPFS=${{ secrets.VITE_API_SECRET_IPFS }} \
          --build-arg VITE_PROTOCOL_REGISTRY_ADDRESS=${{ secrets.VITE_PROTOCOL_REGISTRY_ADDRESS }} \
          --build-arg VITE_VAULT_FACTORY_ADDRESS=${{ secrets.VITE_VAULT_FACTORY_ADDRESS }} \
          --build-arg VITE_RISK_ORACLE_ADDRESS=${{ secrets.VITE_RISK_ORACLE_ADDRESS }} \
          --build-arg VITE_USDC_ADDRESS=${{ secrets.VITE_USDC_ADDRESS }} \
          --build-arg VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }} \
          --build-arg VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY=${{ secrets.VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY }} \
          --build-arg VITE_RPC_URL=${{ secrets.VITE_RPC_URL }} \
          --build-arg VITE_MANTLE_RPC_URL=${{ secrets.VITE_MANTLE_RPC_URL }} \
          --build-arg VITE_RECLAIM_APP_ID=${{ secrets.VITE_RECLAIM_APP_ID }} \
          --build-arg VITE_RECLAIM_APP_SECRET=${{ secrets.VITE_RECLAIM_APP_SECRET }} \
          --build-arg VITE_RECLAIM_PROVIDER_ID=${{ secrets.VITE_RECLAIM_PROVIDER_ID }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
